name: Release
on:
  push:
  
jobs:
  docker-release:
    name: Build and tag release
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: check docker
        id: tag
        run: docker ps
  

