name: Release
on:
  push:
  
jobs:
  docker-release:
    name: Build and tag release
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: check docker
        id: tag
        run: docker ps

      - name: Install .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Build
        run: |
          cd web
          dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer
  

